### ISSUE TITLE
RSS feed is broken

### ISSUE THREAD

**Issue by joschi** [holidaycheck/tech-blog#21]
The RSS feed of the blog at http://techblog.holidaycheck.com/tech-blog/feed.xml (according to the HTML meta data) is broken.

The correct URL is https://holidaycheck.github.io/tech-blog/feed.xml.

**Comment by wolframkriesing** [comment]
Thanks for the finding, I will have an eye on this once we are live at techblog.holidaycheck.com ... I guess I might fix the URL in the project description.
