### ISSUE TITLE
Add the right meta data, to show a nice preview on social media

### ISSUE THREAD

**Issue by wolframkriesing** [holidaycheck/tech-blog#76]
E.g. on twitter when linking a meetup the URL to it might be nicely extended with additional text of the according page. Though this is done differently depending on the twitter client being used.
Figure out and implement the most useful way.
See examples below.
![nsehfrzur0inpxzdcbcvra](https://user-images.githubusercontent.com/113427/33074486-aaa28d92-cec6-11e7-8c45-8f826a5476ac.png)
<img width="266" alt="screen shot 2017-11-21 at 14 13 41" src="https://user-images.githubusercontent.com/113427/33074490-af5e759e-cec6-11e7-9928-90aa23da9e2a.png">

**Comment by Arturszott** [comment]
https://moz.com/blog/meta-data-templates-123

**Comment by Arturszott** [comment]
Done!
